# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: date_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'date_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61te_service.proto\x12\x0b\x64\x61teservice\"e\n\x10\x44\x61teDeltaRequest\x12\x12\n\nbirth_date\x18\x01 \x01(\t\x12\x12\n\nentry_date\x18\x02 \x01(\t\x12\x14\n\x0c\x63urrent_date\x18\x03 \x01(\t\x12\x13\n\x0bmatura_date\x18\x04 \x01(\t\"[\n\x11\x44\x61teDeltaResponse\x12\x13\n\x0b\x61ge_in_days\x18\x01 \x01(\x05\x12\x16\n\x0e\x64\x61ys_in_school\x18\x02 \x01(\x05\x12\x19\n\x11\x64\x61ys_until_matura\x18\x03 \x01(\x05\x32]\n\x0b\x44\x61teService\x12N\n\rCalcDateDelta\x12\x1d.dateservice.DateDeltaRequest\x1a\x1e.dateservice.DateDeltaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'date_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATEDELTAREQUEST']._serialized_start=35
  _globals['_DATEDELTAREQUEST']._serialized_end=136
  _globals['_DATEDELTARESPONSE']._serialized_start=138
  _globals['_DATEDELTARESPONSE']._serialized_end=229
  _globals['_DATESERVICE']._serialized_start=231
  _globals['_DATESERVICE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
